### ISSUE TITLE
"Can't open rtl-sdr device" error after device selection.

### ISSUE THREAD

**Issue by SV8ARJ** [SV8ARJ/spektrum#1]
This seems to be an issue with the drivers and the way that libsdr opens the device.

Symptoms 
-----------
(We assume that you have installed the libusb drivers with [Zadig](https://zadig.akeo.ie) ).
- The _device selection_ drop down list shows two devices (when only one is connected).
- Selecting any of the two produces the "Can't open rtl-sdr device" error and the application exits.
- Other applications work fine (eg HDSDR or SDR#).

Device selection | Error message
:----------------: | :-------------:
![deviceselection01](https://user-images.githubusercontent.com/43477917/45949680-5ba96e00-c005-11e8-8de6-74f1a8cebf22.png) | ![2018-09-24 12_55_26-spektrum](https://user-images.githubusercontent.com/43477917/45949450-9363e600-c004-11e8-9378-091509c44af1.png) 

Fix
---
After installing the drivers with Zadig and having the device connected (This is on a WIN10 machine):
- Open the device  manager and find the device in the Universal Serial Bus Controllers

![devicemissing-removethis](https://user-images.githubusercontent.com/43477917/45950382-3b2ee300-c008-11e8-9917-2ab075fda5bd.png)

- Verify that this is the RTL device by checking the "Hardware IDs". It should have PID_2838.

![devicemissing-pid](https://user-images.githubusercontent.com/43477917/45950525-d1fb9f80-c008-11e8-903b-62f03f6e249f.png)

- Right click on the device and select "Uninstall device"
- After the process is done, remove the RTL USB dongle and reconnect it after 5-10 seconds.
- Wait until the drivers are automatically re-installed.
- Fire up spektrum. If all went well you should see only one device :
![deviceselection02](https://user-images.githubusercontent.com/43477917/45951902-eaba8400-c00d-11e8-88a0-2cb3edcb2a4e.png)

Now everything should be working.

**Comment by Viproz** [comment]
Otherwise I fixed the issue in the code, the deviceId wasn't being passed on, here is the pull request I made : https://github.com/pavels/processing-rtlspektum-lib/pull/2
(I had the issue, this fixes it)

**Comment by SV8ARJ** [comment]
@Viproz 
Nice catch Vincent.
I cannot pull your code to main as it is Pavels.
But since I did modify this very file, I included your fix in the compiled version of rtlspektrum.jar and the binary version of sv-mods v0.19a onward.
Best regards
George

**Comment by Viproz** [comment]
I found another bug in the library, when we set the software to relative mode and back and then on again it does some average with the old value for the previous relative, due to the line :
		}else if(this.relMode != relMode && relMode == RelativeModeType.NONE){
			dbmRelativeBuffer = new double[dbmRelativeBuffer.length];
			for(int i = 0;i<dbmBuffer.length;i++){
				dbmBuffer[i] = Double.POSITIVE_INFINITY;
			}
		}
dbmBuffer should be replaced by dbmRelativeBuffer in the last line, could you publish the modifications you've made to the library so that I can apply the fix ?

Also I've seen a few things that I do not know if they are features or bugs, would you be willing to discuss it directly by email, IRC or something else (I do not have my radio license yet) ?
My email is viproz12 with the usual @gmail.com
