### ISSUE TITLE
Linux build?

### ISSUE THREAD

**Issue by parkerlreed** [SV8ARJ/spektrum#2]
Would be great to have a Linux build as I have zero idea how to work with Processing to get it compiled.

**Comment by SV8ARJ** [comment]
Can you please let me know if the linux build found [here](https://www.dropbox.com/sh/c7vjbvm0mhi4xqu/AAAnuL9OkGZnQfcmRo2nRf8Ia?dl=0)  is OK ?
All my linux boxes are console only !!!
Cheers

**Comment by parkerlreed** [comment]
@SV8ARJ :+1: 
![image](https://user-images.githubusercontent.com/841440/47679329-6d4cdb00-db9a-11e8-8122-4648edd603b5.png)

:D Thanks
