### ISSUE TITLE
Files at wrong place ? Can't run.

### ISSUE THREAD

**Issue by rhaamo** [SV8ARJ/spektrum#3]
Trying to run the file ```spektrum.pde``` from main folder result in error ```The function ifCorrectedFreq(int) does not exist.``` in file ```graph.pde``` line 75.

There is also two ```.pde``` files in ```screenshot``` and if thoses ones are copied in the main directory the program seems to run (not tested further yet).

**Comment by SV8ARJ** [comment]
Latest files uploaded, it should be OK now.
