### ISSUE TITLE
Add crop percentage

### ISSUE THREAD

**Issue by m4rc0d1** [SV8ARJ/spektrum#4]
RTL dongles have no linear gain in the sampling windows (my RTL-SDR.COM has more than 1dB difference between center and edges). This leads to low signal "bumps" every 2MHz where the windows stitch. The common solution is to "crop" the sampling window using the -c switch of rtl_power (-c crop_percent default: 0%, recommended: 20%-50%. Discards data at the edges). This switch instructs rtl_power to compose the spectrogram using the center part of each window discarding the edges. An option that allows to choose the crop factor would be ideal, but a fixed value would be fine (I usually use 30% crop and I get a flat spectrogram with a 50ohm tap at the input).

**Comment by SV8ARJ** [comment]
Hi there.
The crop setting has been included in the latest test build. 
Please test and report.
Note that I modified and recompiled the library rtlspektrum for processing. 
If you want to have a go with source code, you must update it in your lib from the included binaries. 
Cheers
George

**Comment by Viproz** [comment]
Hey,
Thanks for the setting, working perfectly for me :
https://imgur.com/a/5kwjVnq

Images taken with a constant noise source connected to the SDR.

**Comment by SV8ARJ** [comment]
Great !
Thanks for feebback !
Rgrds

**Comment by m4rc0d1** [comment]
Works perfectly!

Thanks
