### ISSUE TITLE
Click and delete key behaviour

### ISSUE THREAD

**Issue by Viproz** [SV8ARJ/spektrum#5]
Hi,

This is more of a feature request/improvement than an issue but posting here for visibility.
The issue I had that was bugging me was the behaviour of the delete key in a text field and not being able to use the mouse to go to a character.

So I fixed it in ControlP5, here is the release with the fix :
https://github.com/Viproz/controlp5/releases/tag/v2.2.7
I had to comment out one line to make it compile as you can see in my commit in the repo.

Tested on my machine, I don't know if the java version I used to compile it matters, might be a good idea to check my build.

**Comment by SV8ARJ** [comment]
What a nice fix !
I replaced the file in the binary with your version and all seems OK.
See if you can push it in the controIP5 repo so it gets into the main branch, not just spektrum !
Cheers !

PS Vincent, once you are there, see id you can implement "Select all text" by double clicking and multiple characters select by mouse dragging.

**Comment by Viproz** [comment]
I submitted a PR, I'll see if anyone is working on the project still.

Text selection is a different matter, you'd need to program how to draw it and modify at least 3 levels, right now if I read it correctly it is not possible to have different font or color of text in the same text, maybe I'll give it a go sometimes.

**Comment by SV8ARJ** [comment]
That’s fine, you already made a major improvement.
Cheers !

**Comment by Viproz** [comment]
I ended up doing it, maybe not the best implementation but it works
https://github.com/Viproz/controlp5/releases/tag/v2.2.7b
